### PR TITLE
Perceiver RNN

### PR DESCRIPTION
**Pull request by JackKelly**

### CODE REVIEW

**Comment by peterdudfield** [comment]
This is still active @JackKelly ?

**Comment by JackKelly** [comment]
Heh, good question!  I'll need to check through the code... but I think I'd like to copy across the comments in the first commit in this PR.  The second commit can probably be thrown away...  I'll try to get this done soon...

**Comment by peterdudfield** [comment]
I'll have a go at copying across comments

**Comment by peterdudfield** [comment]
Comments from this have been moved to this PR - https://github.com/openclimatefix/perceiver-pytorch/pull/15

**Comment by JackKelly** [comment]
Thanks loads, @peterdudfield!  I'll close this pull request now.

At some later stage, I'd still be curious to play with the idea of giving Perceiver IO one-timestep-per-cross-attention, and concatenating each resulting latent array as the input to the decoder... but that can wait (possibly forever!), and will need a new PR anyway...

**Pull request closed without merging**
